# Generated by Django 3.1.5 on 2021-06-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
