# Generated by Django 3.1.5 on 2021-07-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210630_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(default='08.07.2021', max_length=32),
        ),
    ]
